[phases.setup]
nixPkgs = ["xorg.libX11", "xorg.libXext", "glib", "libGL"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8000"